packages:
  - 'apps/*'
  - 'packages/*'
  - 'features/*'
  - 'tools/*'

# Shared dependencies
catalog:
  # React ecosystem
  react: ^19.1.0
  react-dom: ^19.1.0
  '@types/react': ^19.1.0
  '@types/react-dom': ^19.1.0
  
  # TypeScript
  typescript: ^5.7.2
  '@types/node': ^22.11.1
  
  # Build tools
  vite: ^6.1.1
  rollup: ^4.28.0
  esbuild: ^0.24.2
  
  # Testing
  vitest: ^2.2.1
  '@testing-library/react': ^16.1.0
  '@testing-library/jest-dom': ^6.6.3
  
  # Linting
  eslint: ^9.18.0
  '@typescript-eslint/eslint-plugin': ^8.19.0
  '@typescript-eslint/parser': ^8.19.0
  prettier: ^3.4.2
  
  # UI/Styling
  tailwindcss: ^3.5.2
  '@tailwindcss/forms': ^0.5.9
  '@tailwindcss/typography': ^0.5.16
  
  # Utilities
  date-fns: ^4.2.0
  lodash: ^4.17.21
  zod: ^3.24.1
  
  # Icons
  lucide-react: ^0.468.0
  '@heroicons/react': ^2.2.0