packages:
  - 'apps/*'
  - 'packages/*'
  - 'features/*'
  - 'tools/*'

# Shared dependencies
catalog:
  # React ecosystem
  react: ^18.2.0
  react-dom: ^18.2.0
  '@types/react': ^18.2.0
  '@types/react-dom': ^18.2.0
  
  # TypeScript
  typescript: ^5.2.0
  '@types/node': ^20.8.0
  
  # Build tools
  vite: ^5.0.0
  rollup: ^4.0.0
  esbuild: ^0.19.0
  
  # Testing
  vitest: ^1.0.0
  '@testing-library/react': ^14.0.0
  '@testing-library/jest-dom': ^6.1.0
  
  # Linting
  eslint: ^8.50.0
  '@typescript-eslint/eslint-plugin': ^6.7.0
  '@typescript-eslint/parser': ^6.7.0
  prettier: ^3.0.0
  
  # UI/Styling
  tailwindcss: ^3.3.0
  '@tailwindcss/forms': ^0.5.0
  '@tailwindcss/typography': ^0.5.0
  
  # Utilities
  date-fns: ^2.30.0
  lodash: ^4.17.0
  zod: ^3.22.0
  
  # Icons
  lucide-react: ^0.294.0
  '@heroicons/react': ^2.0.0