apiVersion: apps/v1
kind: Deployment
metadata:
  name: pavement-performance-suite
  labels:
    app: pavement-performance-suite
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: pavement-performance-suite
  template:
    metadata:
      labels:
        app: pavement-performance-suite
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - pavement-performance-suite
              topologyKey: kubernetes.io/hostname
      containers:
      - name: pavement-performance-suite
        image: pavement-performance-suite:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
        env:
        - name: NODE_ENV
          value: production
        - name: LOG_LEVEL
          value: info
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: sentry-dsn
      nodeSelector:
        node-type: application
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "pavement-performance"
        effect: "NoSchedule"